"""
Manifest Builder
----------------
Runs discovery (static registry + live scrapers) and writes the two
deliverable files that define the downloadable corpus:

  sources.json  — machine-readable manifest consumed by downloader.py
  SOURCES.md    — human-readable catalog of every source and resource

Both are deterministic given the same discovery results, so they diff
cleanly in git across re-runs.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from sources import SOURCES, SOURCES_BY_ID, static_manifest
import scrapers

log = logging.getLogger(__name__)

MANIFEST_JSON = "sources.json"
MANIFEST_MD   = "SOURCES.md"


def discover(scrape: bool = True, only_sources: list[str] = None,
             opts: dict = None) -> dict:
    """
    Build the full resource manifest.

    scrape=False  -> static registry only (offline, instant)
    scrape=True   -> also run every source's discovery scraper
    only_sources  -> restrict to these source ids
    """
    opts = opts or {}
    resources = [r for r in static_manifest()
                 if not only_sources or r["source"] in only_sources]

    scrape_errors = {}
    if scrape:
        session = scrapers.make_session()
        for src in SOURCES:
            if only_sources and src.id not in only_sources:
                continue
            if not src.scraper:
                continue
            fn = scrapers.SCRAPERS.get(src.scraper)
            if not fn:
                log.warning(f"No scraper registered: {src.scraper}")
                continue
            log.info(f"── Discovering: {src.name}")
            try:
                found = fn(session, opts)
                for r in found:
                    r["discovered_by"] = f"scraper:{src.scraper}"
                resources.extend(found)
            except Exception as e:
                log.error(f"Scraper {src.scraper} crashed: {e}", exc_info=True)
                scrape_errors[src.id] = str(e)

    # Dedupe by URL — static entries win (they may carry curated notes),
    # then first-discovered wins.
    seen, deduped = set(), []
    for r in resources:
        key = r["url"].rstrip("/")
        if key in seen:
            continue
        seen.add(key)
        deduped.append(r)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "uap_pipeline discover",
        "scrape": scrape,
        "scrape_errors": scrape_errors,
        "source_count": len({r["source"] for r in deduped}),
        "resource_count": len(deduped),
        "sources": {
            s.id: {
                "name": s.name, "org": s.org, "homepage": s.homepage,
                "category": s.category, "description": s.description,
                "access": s.access, "scraper": s.scraper, "notes": s.notes,
            } for s in SOURCES
            if not only_sources or s.id in only_sources
        },
        "resources": deduped,
    }


def write_manifest(manifest: dict, out_dir: str = ".") -> tuple[Path, Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    json_path = out / MANIFEST_JSON
    json_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False),
                         encoding="utf-8")

    md_path = out / MANIFEST_MD
    md_path.write_text(render_markdown(manifest), encoding="utf-8")

    log.info(f"Wrote {json_path} ({manifest['resource_count']} resources) "
             f"and {md_path}")
    return json_path, md_path


CATEGORY_TITLES = {
    "us_government":            "U.S. Government",
    "international_government": "International Government",
    "community_archive":        "Community Archives",
    "structured_dataset":       "Structured Datasets",
    "mirror":                   "Mirrors & Redundancy",
}


def render_markdown(manifest: dict) -> str:
    by_source: dict[str, list] = {}
    for r in manifest["resources"]:
        by_source.setdefault(r["source"], []).append(r)

    lines = [
        "# UAP Document Sources",
        "",
        f"> Generated by `python pipeline.py discover` on {manifest['generated_at']}.",
        f"> **{manifest['resource_count']} downloadable resources** across "
        f"**{manifest['source_count']} sources**"
        + (" (live scrape)" if manifest["scrape"] else
           " (static registry only — run with `--scrape` for full per-file enumeration)")
        + ".",
        "",
        "This file is the human-readable view of [`sources.json`](sources.json), "
        "the machine manifest that `pipeline.py download` consumes.",
        "",
    ]

    if manifest.get("scrape_errors"):
        lines += ["## ⚠ Scrape errors", ""]
        for sid, err in manifest["scrape_errors"].items():
            lines.append(f"- **{sid}**: {err}")
        lines.append("")

    for cat, cat_title in CATEGORY_TITLES.items():
        cat_sources = [(sid, meta) for sid, meta in manifest["sources"].items()
                       if meta["category"] == cat]
        if not cat_sources:
            continue
        lines += [f"## {cat_title}", ""]
        for sid, meta in cat_sources:
            res = by_source.get(sid, [])
            lines += [
                f"### {meta['name']}",
                "",
                f"- **Homepage:** {meta['homepage']}",
                f"- **Access:** `{meta['access']}`"
                + (f" (scraper: `{meta['scraper']}`)" if meta["scraper"] else ""),
                f"- **Resources in manifest:** {len(res)}",
                "",
                meta["description"],
                "",
            ]
            if meta["notes"]:
                lines += [f"> {meta['notes']}", ""]
            if res:
                lines += ["| Title | Kind | Size | URL |",
                          "|---|---|---|---|"]
                shown = res if len(res) <= 40 else res[:40]
                for r in shown:
                    title = r["title"].replace("|", "\\|")[:80]
                    size = r.get("size_hint") or ""
                    lines.append(f"| {title} | {r['kind']} | {size} | {r['url']} |")
                if len(res) > 40:
                    lines.append(f"| … and {len(res) - 40} more (see sources.json) | | | |")
                lines.append("")
    lines += [
        "---",
        "",
        "## Coverage notes",
        "",
        "- `manual` sources have no bulk endpoint; their holdings arrive via a "
        "mirror source (noted per-source) or need a human step, and are listed "
        "here so nothing is silently omitted.",
        "- Re-run `python pipeline.py discover --scrape` periodically: war.gov "
        "PURSUE and NARA RG 615 are **rolling releases** and new files appear "
        "throughout the year.",
        "",
    ]
    return "\n".join(lines)
